name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      RAILS_ENV: test
      DATABASE_URL: sqlite3:db/test.sqlite3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6
        bundler-cache: true

    - name: Set up database
      run: |
        bin/rails db:prepare
        bin/rails db:test:prepare

    - name: Run tests
      run: bin/rails test

    - name: Run system tests
      run: bin/rails test:system
